# ===============================================
# Script de déploiement Azure Web App
# Déploie une Web App Linux avec App Service Plan
# ===============================================

param(
    [Parameter(Mandatory=$true)]
    [string]$ResourceGroupName,
    
    [Parameter(Mandatory=$true)]
    [string]$WebAppName,
    
    [Parameter(Mandatory=$true)]
    [string]$Location = "France Central",
    
    [Parameter(Mandatory=$false)]
    [string]$AppServicePlanName = "$WebAppName-plan",
    
    [Parameter(Mandatory=$false)]
    [string]$Sku = "Basic",
    
    [Parameter(Mandatory=$false)]
    [string]$SkuCode = "B1",
    
    [Parameter(Mandatory=$false)]
    [string]$LinuxFxVersion = "PYTHON|3.11",
    
    [Parameter(Mandatory=$false)]
    [string]$TemplateFile = "../arm-template.json"
)

# ===============================================
# Configuration des couleurs pour l'affichage
# ===============================================
$Host.UI.RawUI.ForegroundColor = "White"

function Write-Info {
    param([string]$Message)
    Write-Host "ℹ️  $Message" -ForegroundColor Cyan
}

function Write-Success {
    param([string]$Message)
    Write-Host "✅ $Message" -ForegroundColor Green
}

function Write-Error {
    param([string]$Message)
    Write-Host "❌ $Message" -ForegroundColor Red
}

function Write-Warning {
    param([string]$Message)
    Write-Host "⚠️  $Message" -ForegroundColor Yellow
}

# ===============================================
# Vérification des prérequis
# ===============================================
Write-Info "Vérification des prérequis..."

# Vérifier si Azure CLI est installé
try {
    $azVersion = az version --output tsv --query '"azure-cli"' 2>$null
    if ($azVersion) {
        Write-Success "Azure CLI version $azVersion détecté"
    }
} catch {
    Write-Error "Azure CLI n'est pas installé ou n'est pas dans le PATH"
    exit 1
}

# Vérifier si l'utilisateur est connecté
try {
    $accountInfo = az account show --output tsv --query 'name' 2>$null
    if ($accountInfo) {
        Write-Success "Connecté à Azure: $accountInfo"
    }
} catch {
    Write-Error "Vous n'êtes pas connecté à Azure. Utilisez 'az login'"
    exit 1
}

# ===============================================
# Variables de déploiement
# ===============================================
$subscriptionId = az account show --query id --output tsv
$timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
$deploymentName = "webapp-deployment-$timestamp"

Write-Info "Configuration du déploiement:"
Write-Host "  • Subscription ID: $subscriptionId"
Write-Host "  • Resource Group: $ResourceGroupName"
Write-Host "  • Web App Name: $WebAppName"
Write-Host "  • Location: $Location"
Write-Host "  • App Service Plan: $AppServicePlanName"
Write-Host "  • SKU: $Sku ($SkuCode)"
Write-Host "  • Runtime: $LinuxFxVersion"

# ===============================================
# Création du groupe de ressources
# ===============================================
Write-Info "Vérification/Création du groupe de ressources..."

$rgExists = az group exists --name $ResourceGroupName
if ($rgExists -eq "false") {
    Write-Info "Création du groupe de ressources $ResourceGroupName..."
    az group create --name $ResourceGroupName --location $Location
    if ($LASTEXITCODE -eq 0) {
        Write-Success "Groupe de ressources créé avec succès"
    } else {
        Write-Error "Échec de la création du groupe de ressources"
        exit 1
    }
} else {
    Write-Success "Groupe de ressources $ResourceGroupName existe déjà"
}

# ===============================================
# Déploiement du template ARM
# ===============================================
Write-Info "Démarrage du déploiement ARM..."

# Paramètres pour le template
$parameters = @"
{
    "subscriptionId": {"value": "$subscriptionId"},
    "resourceGroupName": {"value": "$ResourceGroupName"},
    "name": {"value": "$WebAppName"},
    "location": {"value": "$Location"},
    "hostingPlanName": {"value": "$AppServicePlanName"},
    "serverFarmResourceGroup": {"value": "$ResourceGroupName"},
    "alwaysOn": {"value": true},
    "ftpsState": {"value": "Disabled"},
    "autoGeneratedDomainNameLabelScope": {"value": "TenantReuse"},
    "sku": {"value": "$Sku"},
    "skuCode": {"value": "$SkuCode"},
    "workerSize": {"value": "0"},
    "workerSizeId": {"value": "0"},
    "numberOfWorkers": {"value": "1"},
    "linuxFxVersion": {"value": "$LinuxFxVersion"}
}
"@

# Écriture des paramètres dans un fichier temporaire
$paramFile = "parameters-temp.json"
$parameters | Out-File -FilePath $paramFile -Encoding UTF8

try {
    Write-Info "Exécution du déploiement ARM..."
    
    az deployment group create `
        --resource-group $ResourceGroupName `
        --name $deploymentName `
        --template-file $TemplateFile `
        --parameters "@$paramFile" `
        --verbose

    if ($LASTEXITCODE -eq 0) {
        Write-Success "Déploiement ARM terminé avec succès!"
        
        # Récupération des informations de la Web App
        Write-Info "Récupération des informations de déploiement..."
        
        $webAppUrl = az webapp show --name $WebAppName --resource-group $ResourceGroupName --query "defaultHostName" --output tsv
        $webAppState = az webapp show --name $WebAppName --resource-group $ResourceGroupName --query "state" --output tsv
        
        Write-Success "Informations de la Web App:"
        Write-Host "  • Nom: $WebAppName"
        Write-Host "  • URL: https://$webAppUrl"
        Write-Host "  • État: $webAppState"
        Write-Host "  • Groupe de ressources: $ResourceGroupName"
        
        # Configuration de l'application
        Write-Info "Configuration post-déploiement..."
        
        # Configuration des paramètres d'application si nécessaire
        Write-Info "Vous pouvez maintenant configurer vos variables d'environnement avec:"
        Write-Host "az webapp config appsettings set --name $WebAppName --resource-group $ResourceGroupName --settings KEY=VALUE" -ForegroundColor Yellow
        
    } else {
        Write-Error "Échec du déploiement ARM"
        exit 1
    }
    
} catch {
    Write-Error "Erreur durant le déploiement: $_"
    exit 1
} finally {
    # Nettoyage du fichier temporaire
    if (Test-Path $paramFile) {
        Remove-Item $paramFile -Force
    }
}

# ===============================================
# Résumé final
# ===============================================
Write-Success "🎉 Déploiement terminé avec succès!"
Write-Info "Prochaines étapes recommandées:"
Write-Host "1. Configurer les variables d'environnement de votre application"
Write-Host "2. Déployer votre code via Azure CLI, GitHub Actions, ou VS Code"
Write-Host "3. Configurer un nom de domaine personnalisé si nécessaire"
Write-Host "4. Activer Application Insights pour le monitoring"

Write-Host "`n🌐 Votre application est accessible à: https://$webAppUrl" -ForegroundColor Green